package com.pojo;

// Generated 14 Sep, 2017 1:12:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * Pancard generated by hbm2java
 */
public class Pancard implements java.io.Serializable {

	private Integer pid;
	private String pnum;
	private User user;

	public Pancard() {
	}

	public Pancard(String pnum) {
		this.pnum = pnum;
	}

	public Pancard(String pnum, User user) {
		this.pnum = pnum;
		this.user = user;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPnum() {
		return this.pnum;
	}

	public void setPnum(String pnum) {
		this.pnum = pnum;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
